import Head from 'next/head';
import Splash from '../components/Nav/Splash/Splash';
import Nav from '../components/Nav/Nav';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Jams n Jams. N Jams</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Nav />
        <Splash />
      </main>
    </div>
  );
}
